name: 'Continuous Compliance Action'
description: 'An action to generate check for Compliance'
branding:
  icon: lock
  color: purple
inputs:
  ruleset_file_url:
    description: 'url that links to a ruleset config file'
    required: true
    default: 'https://gist.githubusercontent.com/Brend-Smits/385824d3422c0c06323bb1412cd5ba96/raw/e28573211e386e520dc7a1a606fda51abce3429a/gistfile1.txt'
  target_repo:
    description: 'Repository url with access token for repository that needs checking'
    required: true
  gh_token:
    description: 'Github token that has permissions to create labels, issues and has read rights to view files.'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/philips-labs/continuous-compliance:latest'
  args:
    - "lint"
    - "--rulesetUrl"
    - '${{ inputs.ruleset_file_url }}'
    - "-g"
    - 'https://x-access-token:${{ inputs.gh_token }}@github.com/${{ inputs.target_repo }}'