name: 'Continuous Compliance Action'
description: 'An action to generate check for Compliance'
branding:
  icon: lock
  color: purple
inputs:
  ruleset_file_url:
    description: 'url that links to a ruleset config file'
    required: true
    default: 'https://gist.githubusercontent.com/Brend-Smits/385824d3422c0c06323bb1412cd5ba96/raw/08676dbf366a86641dd30fd5511b91afdee65adc/gistfile1.txt'
  gh_token:
    description: 'Github token that has permissions to create labels, issues and has read rights to view files.'
    required: true
  target_repos:
    description: 'Target Repositories (my-org/repository,my-org/repository-2)'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/philips-labs/continuous-compliance:latest'
  args:
    - "${{ inputs.gh_token }}"
    - "${{ inputs.ruleset_file_url }}"
    - "${{ inputs.target_repos }}"