name: Check for compliancy by using the GitHub Action

on:
  workflow_dispatch:

jobs:
  run-linter:
    name: Run Continuous Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: philips-labs/continuous-compliance@develop
        env:
          TARGET_REPO: "Brend-Smits/cc-test-repo"
          GITHUB_TOKEN: ${{ secrets.TEMP_TOKEN }}
        with:
          target_repo: "Brend-Smits/cc-test-repo"
          gh_token: ${{ secrets.TEMP_TOKEN }}