name: Check for compliancy by using the GitHub Action

on:
  workflow_dispatch:
    inputs:
      repository_input:
        description: 'my-org/repository'     
        required: false

jobs:
  run-linter:
    name: Run Continuous Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: philips-labs/continuous-compliance@develop
        env:
          TARGET_REPO: ${{ github.event.inputs.repository_input }}
          GITHUB_TOKEN: ${{ secrets.TEMP_TOKEN }}
        with:
          target_repo: ${{ github.event.inputs.repository_input }}
          gh_token: ${{ secrets.TEMP_TOKEN }}