name: Check for compliancy by using the GitHub Action

on:
  workflow_dispatch:
    inputs:
      target_repos:
        description: 'Target Repositories (my-org/repository,my-org/repository-2)'     
        required: true

jobs:
  run-linter:
    name: Run Continuous Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: philips-labs/continuous-compliance@main
        env:
          target_repos: ${{ github.event.inputs.target_repos }}
          GITHUB_TOKEN: ${{ secrets.TEMP_TOKEN }}
        with:
          target_repos: ${{ github.event.inputs.target_repos }}
          gh_token: ${{ secrets.TEMP_TOKEN }}